version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "thomasvincent"
    labels:
      - "dependencies"
      - "rust"
    rebase-strategy: "auto"
