[package]
name = "find_a_grave_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking", "gzip"] }
scraper = "0.13"
rusqlite = "0.27"
tokio = { version = "1", features = ["full"] }

[features]
default = []
