[package]
name = "find-a-grave-citation-parser"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Rust program that fetches and parses citation information from the Find a Grave website."
license = "MIT"
repository = "https://github.com/your-username/find-a-grave-citation-parser"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.14"
sqlite = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"

[features]
default = ["sqlite-support"]

[build-dependencies]
tokio = { version = "1", features = ["full"] }
